export type RedirectRule =
	| {
			type?: 'exact';
			from: string;
			to: string;
	  }
	| {
			type: 'prefix';
			from: string;
			to: string;
	  }
	| {
			type: 'regex';
			from: string; // JS regex string without flags, e.g. "^/old/(.*)$"
			to: string; // supports $1, $2...
	  };

/**
 * Client-side fallback redirects on the 404 page (HTTP may still be 404 until host-level rules run).
 * Prefer Netlify/Cloudflare `public/_redirects` (generated by scripts/write-redirects.mjs) for real 301s.
 *
 * Notes:
 * - All `from` / `to` should be path-only (start with "/"), not full URLs.
 * - Order matters: first match wins.
 */
export const REDIRECTS: RedirectRule[] = [
	// Legacy flat WordPress paths → canonical nested URLs (SEO).
	{ type: 'regex', from: '^/services-(.+)$', to: '/services/$1' },
	{ type: 'regex', from: '^/locations-(.+)$', to: '/locations/$1' },
	{ type: 'regex', from: '^/prices-(.+)$', to: '/prices/$1' },
];
