export type RedirectRule =
	| {
			type?: 'exact';
			from: string;
			to: string;
	  }
	| {
			type: 'prefix';
			from: string;
			to: string;
	  }
	| {
			type: 'regex';
			from: string; // JS regex string without flags, e.g. "^/old/(.*)$"
			to: string; // supports $1, $2...
	  };

/**
 * Add old URLs here to avoid future 404s.
 *
 * Notes:
 * - All `from` / `to` should be path-only (start with "/"), not full URLs.
 * - Keep them lowercase unless you intentionally rely on case-sensitive paths.
 */
export const REDIRECTS: RedirectRule[] = [
	// Old WP nested paths → new flat slugs generated by this project.
	// Example: /services/sell-used-xbox → /services-sell-used-xbox
	// Example: /locations/kamphaeng-phet → /locations-kamphaeng-phet
	// Example: /prices/switch-oled → /prices-switch-oled
	{ type: 'regex', from: '^/(services|locations|prices)/(.+?)/?$', to: '/$1-$2' },

	// Examples:
	// { from: '/old-page', to: '/new-page' },
	// { type: 'prefix', from: '/blog/', to: '/articles/' },
	// { type: 'regex', from: '^/p/(\\d+)$', to: '/articles/$1' },
];

